# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:latest
      - image: angular/ngcontainer:latest@sha256:e3eee3657b8909a7a9f467f8fa66c24cbf4d353db41ef42ce1e8ab12a181401c

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: xvfb-run -a yarn ci:e2e

      # run deployments for git tags
      - deploy:
          name: Deploy Tag to npm registry
          command: |
            if [ "${CIRCLE_TAG}" ]; then
              npm pack .
              npm publish .
            fi

# trigger builds for git tags
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
deployment:
  trigger_tag:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
